[package]
name = "bare-metal-wasm"
version = "0.1.0"
authors = ["Vincent Khougaz <vincent@khougaz.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[dependencies]
